#!/usr/bin/env python3
"""Build the vault knowledge graph from skills/, vault/ and observations/.

Reads:
  skills/<id>/SKILL.md               the source of truth (never written to)
  vault/notes/<domain>/<id>.md       domain assignment (generated by build.py)
  vault/recipes/*.md                 human-authored hyperedges — the direction source
  .skill-vault/ontology/schema.json  the TBox
  .skill-vault/ontology/lexicon.json artifact vocabulary
  .skill-vault/ontology/assertions/*.json   curated ASSERTED edges
  .skill-vault/observations/*.jsonl  usage episodes

Writes:
  vault/graph/graph.json             the graph, committed and diffable

Design notes live in docs/superpowers/specs/2026-08-12-vault-knowledge-graph-design.md.
Stdlib only, to match CI (python3.12 + unittest, no requirements.txt).

Usage:
  python3 .skill-vault/kg/build_kg.py            # build + report
  python3 .skill-vault/kg/build_kg.py --stats    # report only, no write
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(os.environ.get("SKILL_VAULT_ROOT") or Path(__file__).resolve().parents[2])
SKILLS_DIR = ROOT / "skills"
NOTES_DIR = ROOT / "vault" / "notes"
RECIPES_DIR = ROOT / "vault" / "recipes"
ONTOLOGY_DIR = ROOT / ".skill-vault" / "ontology"
OBSERVATIONS_DIR = ROOT / ".skill-vault" / "observations"
OUT_PATH = ROOT / "vault" / "graph" / "graph.json"

WORD = re.compile(r"[a-z0-9]+")
MAX_NGRAM = 5  # longest skill id is 7 words; 5 covers all but a long tail cheaply
OBSERVED_WEIGHT = 0.05  # start below the 1.0 cap so repeats can accumulate
DISPATCHER = "scientific-agents"

SOURCE_RE = re.compile(r"^source:\s*skills/(.+?)/SKILL\.md\s*$", re.MULTILINE)
ALIASES_RE = re.compile(r"^aliases:\s*\n((?:\s*-\s*.+\n)+)", re.MULTILINE)


# --------------------------------------------------------------------------- io
def load_json(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def discover_skills():
    """Top-level skill folders plus one level of bundled sub-skills (gstack/*)."""
    found = {}
    if not SKILLS_DIR.is_dir():
        return found
    for entry in sorted(os.listdir(SKILLS_DIR)):
        if entry.startswith("."):
            continue
        d = SKILLS_DIR / entry
        if not d.is_dir():
            continue
        if (d / "SKILL.md").is_file():
            found[entry] = d / "SKILL.md"
            continue
        for sub in sorted(os.listdir(d)):
            if (d / sub / "SKILL.md").is_file():
                found[f"{entry}/{sub}"] = d / sub / "SKILL.md"
    return found


def read_frontmatter_description(text):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return ""
    fm = m.group(1)
    dm = re.search(r"^description:\s*(.*?)(?=\n[A-Za-z0-9_-]+:|\Z)", fm, re.DOTALL | re.MULTILINE)
    return " ".join((dm.group(1) if dm else "").split()).strip().strip("'\"")


def load_notes_layer():
    """One pass over vault/notes/<domain>/<id>.md for everything that layer carries.

    Two things live in the same frontmatter, so they are read together:

      * domain assignment, which build.py already generates;
      * curated human synonyms (1572 of 1818 notes carry them) — 'DESeq2' for
        pydeseq2, 'single cell' for scanpy. These are the vault's real controlled
        vocabulary and catch references that never spell the skill id. An alias
        claimed by more than one skill is ambiguous and is dropped rather than
        arbitrarily resolved.
    """
    domains, by_alias = defaultdict(set), defaultdict(set)
    if not NOTES_DIR.is_dir():
        return domains, {}, {}
    for note in sorted(NOTES_DIR.glob("*/*.md")):
        text = note.read_text(encoding="utf-8", errors="replace")[:2000]
        sm = SOURCE_RE.search(text)
        if not sm:
            continue
        sid = sm.group(1)
        domains[sid].add(f"domain:{note.parent.name}")
        am = ALIASES_RE.search(text)
        if not am:
            continue
        for line in am.group(1).splitlines():
            alias = line.strip().lstrip("-").strip().strip("'\"").lower()
            if len(alias) >= 4:  # 3-char aliases are almost all ambiguous acronyms
                by_alias[alias].add(sid)
    resolved = {a: next(iter(s)) for a, s in by_alias.items() if len(s) == 1}
    ambiguous = {a: sorted(s) for a, s in by_alias.items() if len(s) > 1}
    return domains, resolved, ambiguous


# ------------------------------------------------------------------- extraction
def ngram_hits(text, index):
    """Targets named anywhere in `text`, by sweeping its word n-grams against
    `index` (a word-tuple -> target map built by `ngram_index`).

    Inverted so this is O(len(text)) per document rather than O(n_terms) regex
    scans — the naive form does not finish on 1818 skills. Skill ids and curated
    aliases are both matched this way; only the index differs.
    """
    words = WORD.findall(text.lower())
    hits = set()
    for k in range(1, MAX_NGRAM + 1):
        for i in range(len(words) - k + 1):
            target = index.get(tuple(words[i:i + k]))
            if target is not None:
                hits.add(target)
    return hits


def ngram_index(pairs, exact=False):
    """Build a word-tuple -> target index from (term, target) pairs.

    Terms of more than MAX_NGRAM words are dropped: no n-gram can reach them.
    `exact` additionally drops any term that is not exactly its own words joined
    by '-', which is how a skill id must be spelled to be a legitimate hit —
    without it, an id like `gstack/foo` would start matching the bare prose
    "gstack foo".
    """
    index = {}
    for term, target in pairs:
        toks = tuple(WORD.findall(term))
        if not toks or len(toks) > MAX_NGRAM:
            continue
        if exact and "-".join(toks) != term:
            continue
        index[toks] = target
    return index


def high_precision_mentions(text, nameset):
    """Skill ids named in a context that cannot be incidental prose.

    Generic ids (`github`, `workflow`, `start`) appear in 37-42% of bodies as
    ordinary English. Restricting them to these contexts keeps their real
    references without importing the prose noise.
    """
    hits = set()
    for pat in (
        r"`([a-z0-9][a-z0-9./-]*)`",              # backticked
        r"skills/([a-z0-9][a-z0-9./-]*)/SKILL\.md",  # canonical path
        r"\[([a-z0-9][a-z0-9./-]*)\]\(",          # markdown link text
        r"/([a-z0-9][a-z0-9./-]*)\b(?=\s|$)",     # slash-command form
    ):
        for m in re.finditer(pat, text, re.IGNORECASE):
            cand = m.group(1).lower().rstrip("/")
            if cand in nameset:
                hits.add(cand)
    return hits


def parse_recipes(nameset):
    """Recipes are the vault's hyperedges — and its only cheap, trustworthy
    source of *direction*, because the numbered steps are human-authored."""
    recipes = {}
    if not RECIPES_DIR.is_dir():
        return recipes
    for path in sorted(RECIPES_DIR.glob("*.md")):
        if path.name == "index.md":
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        steps, seen = [], set()
        # Ordered steps: numbered list items, in document order. Only the first
        # resolvable link on a line is a step — later links are alternatives
        # or lower-level tools and stay in `members` so they do not form
        # false chains_to edges (pydeseq2 -> rnaseq-de, etc.).
        for line in text.splitlines():
            if not re.match(r"^\s*\d+\.\s", line):
                continue
            primary = True
            for m in re.finditer(r"\[([^\]]+)\]\((?:\.\./)*notes/[^/]+/([a-z0-9.-]+)\.md\)", line):
                sid = m.group(2)
                if sid not in nameset:
                    continue
                if primary and sid not in seen:
                    seen.add(sid)
                    steps.append(sid)
                primary = False
        # Non-step members (Related / alternatives) still co-occur.
        members = set(steps)
        for m in re.finditer(r"\[([^\]]+)\]\((?:\.\./)*notes/[^/]+/([a-z0-9.-]+)\.md\)", text):
            if m.group(2) in nameset:
                members.add(m.group(2))
        title = re.search(r"^title:\s*(.+)$", text, re.MULTILINE)
        recipes[f"recipe:{path.stem}"] = {
            "id": f"recipe:{path.stem}",
            "label": (title.group(1).strip() if title else path.stem),
            "source": f"vault/recipes/{path.name}",
            "steps": steps,
            "members": sorted(members),
        }
    return recipes


def load_disciplines():
    """Discipline assignment for the 503 expert profiles, from the taxonomy that
    already ships in this repo but was not previously part of any graph."""
    path = ROOT / ".skill-vault" / "scientific-expert-taxonomy.json"
    if not path.is_file():
        return {}, {}
    tax = load_json(path)
    titles = {d["id"]: d.get("title", d["id"]) for d in tax.get("disciplines", [])}
    return tax.get("profiles", {}), titles


def load_observations():
    """Usage episodes. Append-only JSONL; malformed lines are skipped, not fatal."""
    episodes = []
    if not OBSERVATIONS_DIR.is_dir():
        return episodes
    for path in sorted(OBSERVATIONS_DIR.glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                ep = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(ep, dict):
                continue
            used = ep.get("used")
            if not isinstance(used, list):
                continue
            episodes.append(ep)
    return episodes


# ------------------------------------------------------------------------ build
class Graph:
    def __init__(self, prov_rank):
        self.prov_rank = prov_rank   # provenance level -> rank, from the TBox
        self.nodes = {}
        self._edges = {}

    def node(self, nid, **attrs):
        self.nodes.setdefault(nid, {"id": nid}).update(attrs)

    def edge(self, src, rel, dst, provenance, justification, weight=1.0, symmetric=False):
        if src == dst:
            return
        key = (src, rel, dst)
        prior = self._edges.get(key)
        if prior:
            # Keep the strongest provenance; accumulate weight.
            if self.prov_rank[provenance] > self.prov_rank[prior["provenance"]]:
                prior["provenance"] = provenance
                prior["justification"] = justification
            prior["weight"] = round(min(1.0, prior["weight"] + 0.05), 4)
        else:
            self._edges[key] = {
                "src": src, "rel": rel, "dst": dst,
                "weight": round(weight, 4),
                "provenance": provenance,
                "justification": justification,
                "status": "accepted" if provenance != "PROPOSED" else "proposed",
            }
        if symmetric:
            self.edge(dst, rel, src, provenance, justification, weight, symmetric=False)

    @property
    def edges(self):
        return list(self._edges.values())


def build():
    schema = load_json(ONTOLOGY_DIR / "schema.json")
    lexicon = load_json(ONTOLOGY_DIR / "lexicon.json")
    policy = schema["extraction_policy"]
    window = policy["body_window_bytes"]
    df_max = policy["distinctive_df_max"]

    skills = discover_skills()
    nameset = set(skills)
    total = len(skills)
    if not total:
        print("no skills found — is SKILL_VAULT_ROOT correct?", file=sys.stderr)
        return None

    profiles, disc_titles = load_disciplines()
    bodies, descs, is_profile = {}, {}, {}
    for sid, path in skills.items():
        text = path.read_text(encoding="utf-8", errors="replace")
        bodies[sid] = text[:window]
        descs[sid] = read_frontmatter_description(text)
        is_profile[sid] = sid in profiles and sid != DISPATCHER

    # Pass 1 — who names whom, plus document frequency for the IDF split.
    name_index = ngram_index(((sid, sid) for sid in nameset), exact=True)
    raw_mentions = {sid: ngram_hits(bodies[sid], name_index) for sid in skills}
    df = Counter()
    for hits in raw_mentions.values():
        for t in hits:
            df[t] += 1
    threshold = total * df_max
    generic = {t for t in nameset if df[t] > threshold}
    distinctive = nameset - generic

    g = Graph({k: v["rank"] for k, v in schema["provenance_levels"].items()})
    domains, alias_map, alias_ambiguous = load_notes_layer()
    aliases_by_sid = defaultdict(list)
    for alias, sid in alias_map.items():
        aliases_by_sid[sid].append(alias)

    for sid in skills:
        g.node(
            sid,
            type="ExpertProfile" if is_profile[sid] else "Skill",
            label=sid,
            description=descs[sid],
            source=f"skills/{sid}/SKILL.md",
            aliases=sorted(aliases_by_sid.get(sid, [])),
            uses=0, successes=0, success_rate=None,
            last_used=None, deprecated=False,
        )
        for d in sorted(domains.get(sid, ())):
            g.node(d, type="Domain", label=d.split(":", 1)[1])
            g.edge(sid, "in_domain", d, "EXTRACTED", "domain from vault/notes layout")

    # references — two-tier, per the measured precision/recall trade-off
    tier1 = tier2 = 0
    for sid in skills:
        for target in raw_mentions[sid] - {sid}:
            if target in distinctive:
                g.edge(sid, "references", target, "EXTRACTED",
                       f"{target} named in {sid}/SKILL.md body", symmetric=True)
                tier1 += 1
        for target in high_precision_mentions(bodies[sid], nameset) - {sid}:
            if target in generic:
                g.edge(sid, "references", target, "EXTRACTED",
                       f"{target} referenced in code/link context in {sid}/SKILL.md",
                       symmetric=True)
                tier2 += 1

    # references via curated aliases — the vault's own controlled vocabulary
    alias_index = ngram_index(alias_map.items())
    alias_df = Counter()
    alias_hits = {}
    for sid in skills:
        found = ngram_hits(bodies[sid], alias_index) - {sid}
        alias_hits[sid] = found
        for t in found:
            alias_df[t] += 1
    alias_edges = 0
    for sid in skills:
        for target in alias_hits[sid]:
            if alias_df[target] > threshold:      # same IDF discipline as skill ids
                continue
            g.edge(sid, "references", target, "EXTRACTED",
                   f"curated alias of {target} appears in {sid}/SKILL.md", symmetric=True)
            alias_edges += 1

    # in_discipline — expert profiles, from the taxonomy already in this repo
    disc_edges = 0
    for sid, spec in profiles.items():
        if sid not in g.nodes:
            continue
        for did in [spec.get("primary")] + list(spec.get("secondary", [])):
            if not did:
                continue
            g.node(f"discipline:{did}", type="Discipline", label=disc_titles.get(did, did))
            g.edge(sid, "in_discipline", f"discipline:{did}", "ASSERTED",
                   "scientific-expert-taxonomy.json")
            disc_edges += 1

    # touches — artifact vocabulary, identified rather than string-matched
    excluded = set(lexicon["excluded_terms"]["terms"])
    art_pats = []
    for aid, spec in lexicon["artifacts"].items():
        g.node(aid, type="Artifact", label=spec["label"])
        if aid.split(":", 1)[1] not in excluded:
            art_pats.append((aid, spec["label"], re.compile(spec["pattern"], re.IGNORECASE)))
    touch_count = 0
    for sid in skills:
        if is_profile[sid]:
            continue  # profiles wrap no tool and exchange no data
        for aid, label, pat in art_pats:
            if pat.search(bodies[sid]):
                g.edge(sid, "touches", aid, "EXTRACTED",
                       f"{label} named in {sid}/SKILL.md")
                touch_count += 1

    # recipes — hyperedges (ASSERTED) and step order (INFERRED direction, rules R2/R3)
    recipes = parse_recipes(nameset)
    for rid, r in recipes.items():
        g.node(rid, type="Recipe", label=r["label"], source=r["source"], steps=r["steps"])
        for sid in r["members"]:
            g.edge(rid, "has_step", sid, "ASSERTED", f"listed in {r['source']}")
        for i, a in enumerate(r["steps"]):
            for b in r["steps"][i + 1:]:
                # INFERRED, not ASSERTED: this is rule R2 deriving co-occurrence
                # from has_step, exactly as R3 derives chains_to. What the human
                # authored is the recipe's step list (has_step, ASSERTED); the
                # pairwise co-occurrence is machinery on top of it. Marking it
                # ASSERTED inflated that level to essentially every reified
                # statement in graph.nq and gave derived edges top merge
                # precedence over real curation.
                g.edge(a, "co_occurs_with", b, "INFERRED",
                       f"co-listed in {r['label']} (rule R2)", symmetric=True)
            if i + 1 < len(r["steps"]):
                nxt = r["steps"][i + 1]
                g.edge(a, "chains_to", nxt, "INFERRED",
                       f"consecutive steps {i+1}->{i+2} in {r['label']} (rule R3)")

    # curated assertions
    assert_dir = ONTOLOGY_DIR / "assertions"
    asserted = 0
    if assert_dir.is_dir():
        for path in sorted(assert_dir.glob("*.json")):
            for e in load_json(path).get("edges", []):
                src, dst, rel = e["src"], e["dst"], e["rel"]
                if src not in g.nodes or dst not in g.nodes:
                    print(
                        f"skip assertion {src} -{rel}-> {dst} in {path.name}: "
                        "unknown endpoint",
                        file=sys.stderr,
                    )
                    continue
                g.edge(src, rel, dst, "ASSERTED",
                       e.get("justification", f"curated in {path.name}"),
                       weight=e.get("weight", 1.0),
                       symmetric=e.get("symmetric", False))
                asserted += 1

    # observations — node statistics and OBSERVED co-occurrence
    episodes = load_observations()
    for ep in episodes:
        used = [s for s in ep.get("used", []) if s in g.nodes]
        ok = ep.get("outcome") == "success"
        for sid in used:
            n = g.nodes[sid]
            n["uses"] += 1
            n["successes"] += int(ok)
            n["success_rate"] = round(n["successes"] / n["uses"], 4)
            ts = ep.get("ts")
            if isinstance(ts, str) and ts and (n["last_used"] is None or ts > n["last_used"]):
                n["last_used"] = ts
        if ok:
            for i, a in enumerate(used):
                for b in used[i + 1:]:
                    g.edge(a, "co_occurs_with", b, "OBSERVED",
                           "co-used in a successful episode",
                           weight=OBSERVED_WEIGHT, symmetric=True)
    # SkillGraph deprecation rule: >=20 uses at <15% success
    for n in g.nodes.values():
        if n.get("uses", 0) >= 20 and (n.get("success_rate") or 0) < 0.15:
            n["deprecated"] = True

    # --- metrics
    # "Orphan" means no skill-to-skill relation. `touches` is deliberately not
    # one: the artifact a skill mentions does not connect it to anything usable.
    # (It used to be listed here, but the `d in nameset` filter below already
    # dropped every artifact, so it never counted — the same drift that CQ6
    # exposed between the metric and its prose.)
    adjacency = defaultdict(set)
    for e in g.edges:
        if e["rel"] in ("references", "co_occurs_with", "chains_to") \
                and e["provenance"] != "PROPOSED":
            adjacency[e["src"]].add(e["dst"])
            adjacency[e["dst"]].add(e["src"])
    skill_ids = list(skills)
    degrees = [len({d for d in adjacency[s] if d in nameset}) for s in skill_ids]
    orphans = [s for s, d in zip(skill_ids, degrees) if d == 0]
    prov_counts = Counter(e["provenance"] for e in g.edges)
    rel_counts = Counter(e["rel"] for e in g.edges)

    metrics = {
        "skills": total,
        "expert_profiles": sum(1 for v in is_profile.values() if v),
        "nodes": len(g.nodes),
        "edges": len(g.edges),
        "generic_names_blocked": len(generic),
        "tier1_edges": tier1,
        "tier2_edges": tier2,
        "alias_edges": alias_edges,
        "discipline_edges": disc_edges,
        "ambiguous_aliases": len(alias_ambiguous),
        "artifact_edges": touch_count,
        "asserted_edges": asserted,
        "recipes": len(recipes),
        "observations": len(episodes),
        "mean_skill_degree": round(sum(degrees) / total, 2),
        "median_skill_degree": sorted(degrees)[total // 2],
        "orphan_count": len(orphans),
        "orphan_rate": round(len(orphans) / total, 4),
        "by_provenance": dict(prov_counts),
        "by_relation": dict(rel_counts),
        # Stamped from the TBox so query.py does not need a second copy of the
        # vocabulary, and does not need to open schema.json to learn it.
        "retrievable_provenance": sorted(
            k for k, v in schema["provenance_levels"].items() if v.get("retrievable")),
    }

    print(f"skills            {total} ({metrics['expert_profiles']} expert profiles)")
    print(f"generic blocked   {len(generic)} names with df > {df_max:.0%} "
          f"({', '.join(sorted(generic)[:8])}...)")
    print(f"nodes / edges     {len(g.nodes)} / {len(g.edges)}")
    print(f"  references      tier1={tier1} tier2={tier2} alias={alias_edges}")
    print(f"  in_discipline   {disc_edges}  ({len(alias_ambiguous)} ambiguous aliases parked)")
    print(f"  touches         {touch_count}")
    print(f"  recipes         {len(recipes)} hyperedges, {asserted} curated assertions")
    print(f"  observations    {len(episodes)} episodes")
    print(f"degree            mean={metrics['mean_skill_degree']} "
          f"median={metrics['median_skill_degree']}")
    print(f"ORPHAN RATE       {metrics['orphan_rate']:.1%} "
          f"({len(orphans)}/{total})   [baseline 48.1%, gate <5%]")
    print(f"by provenance     {dict(prov_counts)}")

    return {
        "schema_version": schema["schema_version"],
        "metrics": metrics,
        "nodes": [g.nodes[k] for k in sorted(g.nodes)],
        "edges": sorted(g.edges, key=lambda e: (e["src"], e["rel"], e["dst"])),
        "recipes": [recipes[k] for k in sorted(recipes)],
        "orphans": sorted(orphans),
        "ambiguous_aliases": {a: v for a, v in sorted(alias_ambiguous.items())},
    }


def main():
    graph = build()
    if graph is None:
        return 1
    if "--stats" in sys.argv:
        return 0
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(graph, indent=1, sort_keys=False) + "\n", encoding="utf-8")
    tmp.replace(OUT_PATH)
    size = OUT_PATH.stat().st_size
    print(f"\nwrote {OUT_PATH.relative_to(ROOT)} ({size/1e6:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
